gdbm: update makefile
$(MAKE1) is used to fix the dependent issue to generate
gram.h before referred.

 gdbmtool.c:20:18: fatal error: gram.h: No such file or directory

Change-Id: Ia0eedc5d7ad0240e0d05ca10840b47d43c2029c2